
language: node_js

node_js:
  - "node"
  - "10"
  - "11"
  - "12"
  - "13"
  - "14"
  - "15"

before_install:
  - npm install -g nyc
  - npm install -g codecov
scripts:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
# after_success:


cache:
  directories:
    - "node_modules"

matrix:
  fast_finish: true
  include:
    # Master channel.
    # All *nix releases are done on the Master channel to take advantage
    # of the regex library's multiple pattern SIMD search.
    - os: windows
      node_js: "node"
    - os: linux
      node_js: "node"
    - os: osx
      node_js: "node"

notifications:
  email:
    on_success: never
