
language: node_js

node_js:
  - "node"
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"

cache:
  directories:
    - "node_modules"

matrix:
  fast_finish: true
  include:
    # Master channel.
    # All *nix releases are done on the Master channel to take advantage
    # of the regex library's multiple pattern SIMD search.
    - os: linux
      node_js: "node"
    - os: osx
      node_js: "node"

notifications:
  email:
    on_success: never
